RVS/RED/RED/Models/DataContext/ArchivedDiary.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RED.Models.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArchivedDiary
    {
        public ArchivedDiary()
        {
            this.ArchivedProducts = new HashSet<ArchivedProduct>();
            this.ArchivedProtocolRemarks = new HashSet<ArchivedProtocolRemark>();
            this.ArchivedProtocolResults = new HashSet<ArchivedProtocolResult>();
        }
    
        public System.Guid Id { get; set; }
        public int Number { get; set; }
        public System.DateTime AcceptanceDateAndTime { get; set; }
        public string LetterNumber { get; set; }
        public System.DateTime LetterDate { get; set; }
        public string Contractor { get; set; }
        public string Client { get; set; }
        public string ClientMobile { get; set; }
        public string Comment { get; set; }
        public System.DateTime RequestDate { get; set; }
        public string RequestAcceptedBy { get; set; }
        public Nullable<int> RequestTestingPeriod { get; set; }
        public System.DateTime ProtocolIssuedDate { get; set; }
        public string ProtocolTester { get; set; }
        public string ProtocolLabLeader { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> AcreditationRegisteredDate { get; set; }
        public Nullable<System.DateTime> AcreditationValidDate { get; set; }
    
        public virtual ICollection<ArchivedProduct> ArchivedProducts { get; set; }
        public virtual ICollection<ArchivedProtocolRemark> ArchivedProtocolRemarks { get; set; }
        public virtual ICollection<ArchivedProtocolResult> ArchivedProtocolResults { get; set; }
    }
}

RVS/RED/RED/Controllers/ArchivedDiaryController.cs
using System;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using RED.Filters;
using RED.Models.ControllerBases;
using RED.Models.ElectronicDiary;
using RED.Models.ElectronicDiary.ArchivedWrappers;
using RED.Repositories.Abstract;

namespace RED.Controllers
{
    [UserFilter]
    public class ArchivedDiaryController : BaseController
    {
        private readonly IArchivedDiaryRepository _rep;

        public ArchivedDiaryController(IArchivedDiaryRepository archivedDiaryRepo)
        {
            _rep = archivedDiaryRepo;
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Edit(Guid id)
        {
            var archivedDiary = _rep.GetArchivedDiaryW(id);
            return View(archivedDiary);
        }

        [HttpPost]
        public ActionResult Edit(ArchivedDiaryW adiary)
        {
            if (ModelState.IsValid)
            {
                _rep.Edit(adiary);
                return RedirectToAction("Index", "Diary");
            }

            return View(adiary);
        }

        public ActionResult ProductsIndex(Guid archivedDiaryId)
        {
            var adiary = _rep.GetArchivedDiary(archivedDiaryId);
            ViewBag.ADiaryNumber = adiary.Number;
            ViewBag.ArchivedDiaryId = archivedDiaryId;
            return View();
        }

        public JsonResult GetProducts(Guid archivedDiaryId)
        {
            var products = _rep.GetProducts(archivedDiaryId).OrderBy(p => p.Number);
            return Json(new { data = products }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult CreateProduct(Guid archivedDiaryId)
        {
            ViewBag.ADiaryId = archivedDiaryId;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateProduct(ArchivedProductW aproduct)
        {
            if (ModelState.IsValid)
            {
                _rep.AddProduct(aproduct);
                return RedirectToAction("ProductsIndex", new { archivedDiaryId = aproduct.ArchivedDiaryId });
            }

            return View(aproduct);
        }

        [HttpGet]
        public ActionResult EditProduct(Guid id)
        {
            var aproduct = _rep.GetArchivedProductW(id);
            ViewBag.ADiaryId = aproduct.ArchivedDiaryId;
            return View(aproduct);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditProduct(ArchivedProductW aproduct)
        {
            if (ModelState.IsValid)
            {
                _rep.EditProduct(aproduct);
                return RedirectToAction("ProductsIndex", new { archivedDiaryId = aproduct.ArchivedDiaryId });
            }

            return View(aproduct);
        }

        [HttpGet]
        public ActionResult DeleteProduct(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var aproduct = _rep.GetArchivedProductW(id.Value);
            if (aproduct == null)
            {
                return HttpNotFound();
            }

            if (Request.IsAjaxRequest())
            {
                return PartialView(aproduct);
            }

            return View(aproduct);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteProduct(Guid id)
        {
            var product = _rep.GetArchivedProduct(id);
            bool isdeleted = _rep.DeleteProduct(id);

            if (isdeleted)
            {
                return RedirectToAction("ProductsIndex", new { archivedDiaryId = product.ArchivedDiaryId });
            }

            return RedirectToAction("DeleteConflicted", "Error", new { returnUrl = "/ArchivedDiary/ProductsIndex?archivedDiaryId=" + product.ArchivedDiaryId });
        }

        public ActionResult ProductTestsIndex(Guid aproductId)
        {
            var aproduct = _rep.GetArchivedProductW(aproductId);
            ViewBag.ArchivedProductId = aproductId;
            ViewBag.AProductName = aproduct.Name;

            return View();
        }

        public JsonResult GetProductTests(Guid aproductId)
        {
            var products = _rep.GetProductTests(aproductId);
            return Json(new { data = products }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult CreateProductTest(Guid aproductId)
        {
            ViewBag.TestAcredetationLevel = new SelectList(_rep.GetPossibleAcredetationLevels(), "Level", "Level");
            ViewBag.AProductId = aproductId;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateProductTest(ArchivedProductTestW aproductTest)
        {
            if (ModelState.IsValid)
            {
                _rep.AddProductTest(aproductTest);
                return RedirectToAction("ProductTestsIndex", new { aproductId = aproductTest.ArchivedProductId });
            }

            return View(aproductTest);
        }

        [HttpGet]
        public ActionResult EditProductTest(Guid aproductTestId)
        {
            var aProductTest = _rep.GetArchivedProductTestW(aproductTestId);
            ViewBag.TestAcredetationLevel = new SelectList(_rep.GetPossibleAcredetationLevels(), "Level", "Level", aProductTest.TestAcredetationLevel);
            ViewBag.AProductId = aProductTest.ArchivedProductId;
            return View(aProductTest);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditProductTest(ArchivedProductTestW aproductTest)
        {
            if (ModelState.IsValid)
            {
                _rep.EditProductTest(aproductTest);
                return RedirectToAction("ProductTestsIndex", new { aproductId = aproductTest.ArchivedProductId });
            }

            return View(aproductTest);
        }

        [HttpGet]
        public ActionResult DeleteProductTest(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var aproductTest = _rep.GetArchivedProductTestW(id.Value);
            if (aproductTest == null)
            {
                return HttpNotFound();
            }

            if (Request.IsAjaxRequest())
            {
                return PartialView(aproductTest);
            }

            return View(aproductTest);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteProductTest(Guid id)
        {
            var productTest = _rep.GetArchivedProductTest(id);
            bool isdeleted = _rep.DeleteProductTest(id);

            if (isdeleted)
            {
                return RedirectToAction("ProductTestsIndex", new { aproductId = productTest.ArchivedProductId });
            }

            return RedirectToAction("DeleteConflicted", "Error", new { returnUrl = "/ArchivedDiary/ProductTestsIndex?aproductId=" + productTest.ArchivedProductId });
        }

        public ActionResult ProtocolResultsIndex(Guid aproductTestId)
        {
            var aproductTest = _rep.GetArchivedProductTestW(aproductTestId);
            ViewBag.ArchivedProductTestId = aproductTestId;
            ViewBag.AProductTestName = aproductTest.TestName;

            return View();
        }

        public JsonResult GetProtocolResults(Guid aproductTestId)
        {
            var products = _rep.GetProtocolResults(aproductTestId);
            return Json(new { data = products }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult CreateProtocolResult(Guid aproductTestId)
        {
            var productTest = _rep.GetArchivedProductTestW(aproductTestId);
            var product = _rep.GetArchivedProductW(productTest.ArchivedProductId);

            ViewBag.ADiaryId = product.ArchivedDiaryId;
            ViewBag.AProductTestId = aproductTestId;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateProtocolResult(ArchivedProtocolResultW aprotocolResult)
        {
            if (ModelState.IsValid)
            {
                _rep.AddProtocolResult(aprotocolResult);
                return RedirectToAction("ProtocolResultsIndex", new { aproductTestId = aprotocolResult.ArchivedProductTestId });
            }

            return View(aprotocolResult);
        }

        [HttpGet]
        public ActionResult EditProtocolResult(Guid aprotocolResultId)
        {
            var aprotocolResult = _rep.GetArchivedProtocolResultW(aprotocolResultId);
            ViewBag.AProductTestId = aprotocolResult.ArchivedProductTestId;
            return View(aprotocolResult);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditProtocolResult(ArchivedProtocolResultW aprotocolResult)
        {
            if (ModelState.IsValid)
            {
                _rep.EditProtocolResult(aprotocolResult);
                return RedirectToAction("ProtocolResultsIndex", new { aproductTestId = aprotocolResult.ArchivedProductTestId });
            }

            return View(aprotocolResult);
        }

        [HttpGet]
        public ActionResult DeleteProtocolResult(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var aprotocolResult = _rep.GetArchivedProtocolResultW(id.Value);
            if (aprotocolResult == null)
            {

RVS/RED/RED/Views/ArchivedDiary/CreateProduct.cshtml
@model RED.Models.ElectronicDiary.ArchivedWrappers.ArchivedProductW

<h2>Добави</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Продукт</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        
        <input type="hidden" id="ArchivedDiaryId" name="ArchivedDiaryId" value="@ViewBag.ADiaryId" />

        <div class="form-group">
            @Html.LabelFor(model => model.Number, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Number, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Number, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <a href="/ArchivedDiary/ProductsIndex?archivedDiaryId=@ViewBag.ADiaryId" class="btn btn-default">Отказ</a>
                <input type="submit" value="Създай" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

RVS/RED/RED/Views/ArchivedDiary/CreateProductTest.cshtml
@model RED.Models.ElectronicDiary.ArchivedWrappers.ArchivedProductTestW

<h2>Добави</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Изследване</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <input type="hidden" id="ArchivedProductId" name="ArchivedProductId" value="@ViewBag.AProductId" />
        <div class="form-group">
            @Html.LabelFor(model => model.TestCategory, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TestCategory, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TestCategory, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TestName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TestName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TestName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TestMethods, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TestMethods, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TestMethods, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TestAcredetationLevel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TestAcredetationLevel", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TestAcredetationLevel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TestUnitName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TestUnitName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TestUnitName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TestTemperature, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TestTemperature, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TestTemperature, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="button" value="±" class="btn btn-xs btn-info" style="padding:0 22px;" for="TestTemperature" onclick="addSign(this)" />
                <input type="button" value="°" class="btn btn-xs btn-info" style="padding:0 22px;" for="TestTemperature" onclick="addSign(this)" />
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.TestType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TestType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TestType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TestTypeShortName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TestTypeShortName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TestTypeShortName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MethodValue, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MethodValue, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MethodValue, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="button" value="±" class="btn btn-xs btn-info" style="padding:0 22px;" for="MethodValue" onclick="addSign(this)" />
                <input type="button" value="°" class="btn btn-xs btn-info" style="padding:0 22px;" for="MethodValue" onclick="addSign(this)" />
                <input type="button" value="²" class="btn btn-xs btn-info" style="padding:0 22px;" for="MethodValue" onclick="addSign(this)" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <a href="/ArchivedDiary/ProductTestsIndex?aproductId=@ViewBag.AProductId" class="btn btn-default">Отказ</a>
                <input type="submit" value="Създай" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

RVS/RED/RED/Views/ArchivedDiary/CreateProtocolResult.cshtml
@model RED.Models.ElectronicDiary.ArchivedWrappers.ArchivedProtocolResultW

<h2>Добави</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Резултат</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        
        <input type="hidden" name="ArchivedDiaryId" value="@ViewBag.ADiaryId" />
        <input type="hidden" name="ArchivedProductTestId" value="@ViewBag.AProductTestId" />

        <div class="form-group">
            @Html.LabelFor(model => model.ResultNumber, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.ResultNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ResultNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Results, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.TextAreaFor(model => model.Results, new {  @class = "form-control tarea" })
                @Html.ValidationMessageFor(model => model.Results, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-3 col-md-9">
                <input type="button" value="±" class="btn btn-xs btn-info" style="padding:0 22px;" for="Results" onclick="addSign(this)" />
                <input type="button" value="°" class="btn btn-xs btn-info" style="padding:0 22px;" for="Results" onclick="addSign(this)" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-3 col-md-9">
                <a href="/ArchivedDiary/ProtocolResultsIndex?aproductTestId=@ViewBag.AProductTestId" class="btn btn-default">Отказ</a>
                <input type="submit" value="Създай" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

RVS/RED/RED/Views/ArchivedDiary/DeleteProduct.cshtml
@model RED.Models.ElectronicDiary.ArchivedWrappers.ArchivedProductW

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Затвори</span></button>
    <i class="fa fa-beer modal-icon"></i>
    <h4 class="modal-title">Изтрий</h4>
    <small class="font-bold">Сигурни ли сте, че искате да изтриете тoзи продукт?</small>
</div>
<div class="modal-body">
    <h4 class="text-center">Този продукт е свързан със следните изследвания:</h4>
    <ol style="padding-left: 86px;">
        @foreach(var test in Model.ArchivedTests)
        {
            <li>@test.TestName</li>
        }
    </ol>
</div>
<div class="modal-footer">
    @using (Html.BeginForm("DeleteProduct", "ArchivedDiary", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        @Html.HiddenFor(m => m.Id)
        <div class="form-actions no-color">
            <input type="submit" value="Да" class="btn btn-primary btn-padding-lg" />
            <button type="button" class="btn btn-white btn-padding-lg" data-dismiss="modal">Не</button>
        </div>
    }
</div>

RVS/RED/RED/Views/ArchivedDiary/DeleteProductTest.cshtml
@model RED.Models.ElectronicDiary.ArchivedWrappers.ArchivedProductTestW

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Затвори</span></button>
    <i class="fa fa-area-chart modal-icon"></i>
    <h4 class="modal-title">Изтрий</h4>
    <small class="font-bold">Сигурни ли сте, че искате да изтриете тoва изследване?</small>
</div>
<div class="modal-body">
    <h4 class="text-center">Това изследване е свързано със следните резултати:</h4>
    <ol style="padding-left: 86px;">
        @foreach (var result in Model.Results)
        {
            <li>@result.ResultNumber</li>
        }
    </ol>
</div>
<div class="modal-footer">
    @using (Html.BeginForm("DeleteProductTest", "ArchivedDiary", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        @Html.HiddenFor(m => m.Id)
        <div class="form-actions no-color">
            <input type="submit" value="Да" class="btn btn-primary btn-padding-lg" />
            <button type="button" class="btn btn-white btn-padding-lg" data-dismiss="modal">Не</button>
        </div>
    }
</div>

RVS/RED/RED/Views/ArchivedDiary/DeleteProtocolResult.cshtml
@model RED.Models.ElectronicDiary.ArchivedWrappers.ArchivedProtocolResultW

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Затвори</span></button>
    <i class="fa fa-flask modal-icon"></i>
    <h4 class="modal-title">Изтрий</h4>
    <small class="font-bold">Сигурни ли сте, че искате да изтриете тoзи резултат?</small>
</div>
<div class="modal-body">
    
</div>
<div class="modal-footer">
    @using (Html.BeginForm("DeleteProtocolResult", "ArchivedDiary", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        @Html.HiddenFor(m => m.Id)
        <div class="form-actions no-color">
            <input type="submit" value="Да" class="btn btn-primary btn-padding-lg" />
            <button type="button" class="btn btn-white btn-padding-lg" data-dismiss="modal">Не</button>
        </div>
    }
</div>

RVS/RED/RED/Views/ArchivedDiary/EditProduct.cshtml
@model RED.Models.ElectronicDiary.ArchivedWrappers.ArchivedProductW

<h2>Промени</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Продукт</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <input type="hidden" id="ArchivedDiaryId" name="ArchivedDiaryId" value="@ViewBag.ADiaryId" />

        <div class="form-group">
            @Html.LabelFor(model => model.Number, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Number, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Number, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <a href="/ArchivedDiary/ProductsIndex?archivedDiaryId=@ViewBag.ADiaryId" class="btn btn-default">Отказ</a>
                <input type="submit" value="Запази" class="btn btn-primary" />
                <a href="/ArchivedDiary/ProductTestsIndex?aproductId=@Model.Id" class="btn btn-info">Промени изследвания</a>
            </div>
        </div>
    </div>
}

RVS/RED/RED/Views/ArchivedDiary/EditProtocolResult.cshtml
@model RED.Models.ElectronicDiary.ArchivedWrappers.ArchivedProtocolResultW

<h2>Промени</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Резултат</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.ArchivedDiaryId)
        @Html.HiddenFor(model => model.ArchivedProductTestId)

        <div class="form-group">
            @Html.LabelFor(model => model.ResultNumber, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.EditorFor(model => model.ResultNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ResultNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Results, htmlAttributes: new { @class = "control-label col-md-3" })
            <div class="col-md-9">
                @Html.TextAreaFor(model => model.Results, new { @class = "form-control tarea" })
                @Html.ValidationMessageFor(model => model.Results, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-3 col-md-9">
                <input type="button" value="±" class="btn btn-xs btn-info" style="padding:0 22px;" for="Results" onclick="addSign(this)" />
                <input type="button" value="°" class="btn btn-xs btn-info" style="padding:0 22px;" for="Results" onclick="addSign(this)" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-3 col-md-9">
                <a href="/ArchivedDiary/ProtocolResultsIndex?aproductTestId=@ViewBag.AProductTestId" class="btn btn-default">Отказ</a>
                <input type="submit" value="Запази" class="btn btn-primary" />
            </div>
        </div>
    </div>
}